
import React from 'react'

const Debebe = () => {
    return (
        <div style = {{display: 'flex'}}>
            
            <p>Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah
                Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah
                Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah
                Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah
                Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuahFenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah Fenan is coming for you wuah wuah wuah
            </p>

        </div>
    )
}
export default Debebe